### ISSUE TITLE
Using the latest version panics on `github.com/grafana/dashboard-linter/lint.getConfiguredUnit`

### ISSUE THREAD

**Issue by gotjosh** [monitoring-mixins/mixtool#135]
After https://github.com/monitoring-mixins/mixtool/commit/2282201396b69055bb0f92f187049027a16d2130 but using `mixtool lint` on the Alertmanager mixin panics (You can see the error output in [here](https://app.circleci.com/pipelines/github/prometheus/alertmanager/3693/workflows/70d170cc-65c0-421f-84aa-7b94dea2abd7/jobs/16298)).

I believe the failure to be coming from the upgrade to github.com/grafana/dashboard-linter on https://github.com/monitoring-mixins/mixtool/pull/133

**Comment by gotjosh** [comment]
Managed to trace it to looking at https://github.com/grafana/dashboard-linter/compare/1e2783473c77473a812f5583a6db8a5c6b6338df..fca179a60f4f59bff8dd483d92f5a04732f81d8d so I filed https://github.com/grafana/dashboard-linter/pull/143

**Comment by tomwilkie** [comment]
Sorry about this Josh! Looking at this now.

**Comment by rgeyer** [comment]
@gotjosh Sorry that this got overlooked for so long! @tomwilkie Thank you for getting it all sorted out.

Josh, I saw that you reopened the issue shortly after closing it. Is there still an issue, or is there a new issue?

**Comment by gotjosh** [comment]
No worries @rgeyer - I appreciate the effort.

I re-opened because I noticed that https://github.com/monitoring-mixins/mixtool/pull/140 wasn't merged and was then closed.

With the merge of https://github.com/monitoring-mixins/mixtool/pull/141 we should def close it.
