### ISSUE TITLE
mixtool lint doesn't support Prometheus functions for native histograms

### ISSUE THREAD

**Issue by pstibrany** [monitoring-mixins/mixtool#163]
Mixtool lint fails when alerts use functions for native histograms, like `histogram_count` or `histogram_sum`.

```
could not parse expression: 2:5: parse error: unknown function with name "histogram_sum"
```

**Comment by krajorama** [comment]
I think it's using the Prometheus codebase to do the parsing of the expressions so you need #164 for this

**Comment by krajorama** [comment]
And #164 that depends on #165

**Comment by tomwilkie** [comment]
Should be all fixed now!
