### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by roidelapluie** [monitoring-mixins/mixtool#40]
Since #39, Mixtool depends on Grafana's AGPL code as in `github.com/grafana/grafana/pkg/`. Therefore, mixtool can not be distributed under Apache-2 License.The pkg directory is not excluded in https://github.com/grafana/grafana/blob/main/LICENSING.md

**Comment by rgeyer** [comment]
Ohhff.. That is an excellent point, and entirely my fault. Apologies for the oversight. I'll give this some thought and see if there is a suitable solution.
