### ISSUE TITLE
Linting false positives

### ISSUE THREAD

**Issue by mshahzeb** [monitoring-mixins/mixtool#57]
Issue # 1
Getting error with dashboard linter: "[template-job-rule] 'Asterisk - Overview': Dashboard 'Asterisk - Overview' job template should use datasource '$datasource'" for the json dashboard attached.
[asterisk-overview.json.zip](https://github.com/monitoring-mixins/mixtool/files/8081591/asterisk-overview.json.zip)

The linter expects datasource to be "$datasource" however copying JSON from Grafana sets this variable as "${datasource}"

Issue # 2
[template-job-rule] 'Asterisk - Overview': Dashboard 'Asterisk - Overview' job template should be a labelled 'job'

If you look at the dashboard JSON file - the job temlpate already has a label.

**Comment by tomwilkie** [comment]
Hi @mshahzeb! Thanks for filling the issues.  Do you mind filling these as two separate issues over on https://github.com/grafana/dashboard-linter? We use that code for mixtool lint.  They should be pretty straight forward to fix.

**Comment by mshahzeb** [comment]
Hi @tomwilkie Created these as 2 separate issues in https://github.com/grafana/dashboard-linter

https://github.com/grafana/dashboard-linter/issues/26
https://github.com/grafana/dashboard-linter/issues/27

**Comment by tomwilkie** [comment]
Thank you! I'll close this one.
