### ISSUE TITLE
Rename default branch to `main`

### ISSUE THREAD

**Issue by rgeyer** [monitoring-mixins/mixtool#78]
Anyone opposed to renaming the default branch per [these instructions](https://github.com/github/renaming)?

I'll let this marinate until June 10th 2022. If I don't hear any objections, I'll make the change.

cc: @tomwilkie @metalmatze.. Anyone else?

**Comment by tomwilkie** [comment]
It +1 from me

**Comment by rgeyer** [comment]
Completed!
